
CREATE TABLE IF NOT EXISTS `acheumprofissional`.`JOB_CATEGORY` (
  `JOB_CATEGORY_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(150) NOT NULL,
  `STATUS` CHAR(1) NOT NULL,
  PRIMARY KEY (`JOB_CATEGORY_ID`))
ENGINE = InnoDB

ALTER TABLE JOB_CATEGORY MODIFY COLUMN STATUS CHAR(1);

CREATE TABLE IF NOT EXISTS `acheumprofissional`.`WORKER` (
  `WORKER_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(60) NOT NULL,
  `LAST_NAME` VARCHAR(100) NOT NULL,
  `JOB_CATEGORY_ID` BIGINT NOT NULL,
  `USERNAME` VARCHAR(50) NOT NULL,
  `PWD` VARCHAR(150) NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `PHONE` VARCHAR(16) NOT NULL,
  `EMAIL` VARCHAR(100) NULL,
  `BIRTH` VARCHAR(10) NOT NULL,
  `IMAGE_THUMB` MEDIUMBLOB NULL,
  `DESCRIPTION` VARCHAR(200) NULL,
  `RECOMMENDATIONS` INT NULL,
  `STATUS` CHAR(1) NOT NULL,
  PRIMARY KEY (`WORKER_ID`),
  INDEX `fk_WORKER_JOB_CATEGORY_idx` (`JOB_CATEGORY_ID` ASC),
  CONSTRAINT `fk_WORKER_JOB_CATEGORY`
    FOREIGN KEY (`JOB_CATEGORY_ID`)
    REFERENCES `acheumprofissional`.`JOB_CATEGORY` (`JOB_CATEGORY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

ALTER TABLE WORKER ADD EMAIL VARCHAR(100); 

ALTER TABLE WORKER MODIFY COLUMN DESCRIPTION VARCHAR(200);

CREATE TABLE IF NOT EXISTS `acheumprofissional`.`CONTRACTOR` (
  `CONTRACTOR_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(60) NOT NULL,
  `LAST_NAME` VARCHAR(100) NOT NULL,
  `USERNAME` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(100) NULL,
  `PWD` VARCHAR(150) NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `STATUS` CHAR(1) NOT NULL,
  PRIMARY KEY (`CONTRACTOR_ID`))
ENGINE = InnoDB

ALTER TABLE CONTRACTOR ADD EMAIL VARCHAR(100);

ALTER TABLE CONTRACTOR MODIFY PWD VARCHAR(150);

CREATE TABLE IF NOT EXISTS `acheumprofissional`.`WORKER_VIEWS` (
  `WORKER_VIEWS_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `CONTRACTOR_ID` BIGINT NOT NULL,
  `WORKER_ID` BIGINT NOT NULL,
  INDEX `fk_WORKER_VIEWS_WORKER1_idx` (`WORKER_ID` ASC),
  PRIMARY KEY (`WORKER_VIEWS_ID`),
  CONSTRAINT `fk_WORKER_VIEWS_CONTRACTOR1`
    FOREIGN KEY (`CONTRACTOR_ID`)
    REFERENCES `acheumprofissional`.`CONTRACTOR` (`CONTRACTOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WORKER_VIEWS_WORKER1`
    FOREIGN KEY (`WORKER_ID`)
    REFERENCES `acheumprofissional`.`WORKER` (`WORKER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `acheumprofissional`.`CONTRACTOR_WORKER_RECOMMENDATION` (
  `CONTRACTOR_WORKER_RECOMMENDATION_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `WORKER_ID` BIGINT NOT NULL,
  `CONTRACTOR_ID` BIGINT NOT NULL,
  PRIMARY KEY (`CONTRACTOR_WORKER_RECOMMENDATION_ID`, `WORKER_ID`, `CONTRACTOR_ID`),
  INDEX `fk_CONTRACTOR_WORKER_RECOMMENDATION_WORKER1_idx` (`WORKER_ID` ASC),
  INDEX `fk_CONTRACTOR_WORKER_RECOMMENDATION_CONTRACTOR1_idx` (`CONTRACTOR_ID` ASC),
  CONSTRAINT `fk_CONTRACTOR_WORKER_RECOMMENDATION_WORKER1`
    FOREIGN KEY (`WORKER_ID`)
    REFERENCES `acheumprofissional`.`WORKER` (`WORKER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONTRACTOR_WORKER_RECOMMENDATION_CONTRACTOR1`
    FOREIGN KEY (`CONTRACTOR_ID`)
    REFERENCES `acheumprofissional`.`CONTRACTOR` (`CONTRACTOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `acheumprofissional`.`FORGOT_PWD` (
  `FORGOT_PWD_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `TYPE` CHAR(1) NOT NULL,
  `USERNAME` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `TOKEN` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`FORGOT_PWD_ID`))
ENGINE = InnoDB

